@url = http://localhost:8000/api
//Genera un token
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3JlZ2lzdGVyIiwiaWF0IjoxNzMyNDY5NDY0LCJleHAiOjE3MzI0NzMwNjQsIm5iZiI6MTczMjQ2OTQ2NCwianRpIjoiSU5ZdGRxN3VaTGFqbm9UWCIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.Q6L0qaE24aG7QA8ix5q15Ee3SVB6O_FWqpbf0JAJuvI



### Register a user
POST {{url}}/register/ HTTP/1.1
content-type: application/json

{
    "name":"nicolas2",
    "email":"nicolas2@admin.com",
    "password":"12345678"
}

### Login a user
POST {{url}}/login/ HTTP/1.1
content-type: application/json

{
   "email":"nicolas2@admin.com",
    "password":"12345678"
}

### export a product
GET {{url}}/products/export/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Get all products
GET {{url}}/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
### store a product
POST {{url}}/products/ HTTP/1.1
Authorization: token {{token}}
content-type: application/json

{
    "name":"salsa de tomate",
    "price":22,
    "stock":15
}

### show a product
GET {{url}}/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### update a product
PUT {{url}}/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"papas margarita",
    "price":22,
    "stock":15
}

### delete a product
DELETE {{url}}/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
////// Orders //////

### Get all orders
GET {{url}}/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
### store a order
POST {{url}}/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
{
        "status":"pending",
        "total_amount" : 22.00,
        "payment_status": "refunded",
        "payment_method": "credit_card" ,
        "shipping_address": "car 7 # 40B 130",
        "billing_address" : "car 7 # 40B 130",
        "shipping_fee":0,
        "discount": 0,
        "notes":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        "product_id": 9,
        "total_price":"2222"
}

### show a order
GET {{url}}/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
### update a order
PUT {{url}}/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
        "status":"completed",
        "total_amount" : 22.00,
        "payment_status": "refunded",
        "payment_method": "credit_card" ,
        "shipping_address": "car 7 # 40B 130",
        "billing_address" : "car 7 # 40B 130",
        "shipping_fee":0,
        "discount": 0,
        "notes":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        "product_id": 9,
        "total_price":"2222"
}

### delete a order
DELETE {{url}}/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
