@url = http://127.0.0.1:8000/api



### Get all products
GET {{url}}/products/ HTTP/1.1

### store a product
POST {{url}}/products/ HTTP/1.1
content-type: application/json

{
    "name":"salsa de tomate",
    "price":22,
    "stock":15
}

### show a product
GET {{url}}/products/1/ HTTP/1.1


### update a product
PUT {{url}}/products/1/ HTTP/1.1
content-type: application/json

{
    "name":"papas margarita",
    "price":22,
    "stock":15
}

### delete a product
DELETE {{url}}/products/1/ HTTP/1.1

////// Orders //////

### Get all orders
GET {{url}}/orders/ HTTP/1.1

### store a order
POST {{url}}/orders/ HTTP/1.1
content-type: application/json

{
        "status":"pending",
        "total_amount" : 22.00,
        "payment_status": "refunded",
        "payment_method": "credit_card" ,
        "shipping_address": "car 7 # 40B 130",
        "billing_address" : "car 7 # 40B 130",
        "shipping_fee":0,
        "discount": 0,
        "notes":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        "product_id": 9,
        "total_price":"2222"
}

### show a order
GET {{url}}/orders/1/ HTTP/1.1

### update a order
PUT {{url}}/orders/1/ HTTP/1.1
content-type: application/json
bearer token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjIwNjYwNjY5LCJlbWFpbCI6ImFkbWluQG1haWwuY29tIn0.1J9Z6

{
        "status":"completed",
        "total_amount" : 22.00,
        "payment_status": "refunded",
        "payment_method": "credit_card" ,
        "shipping_address": "car 7 # 40B 130",
        "billing_address" : "car 7 # 40B 130",
        "shipping_fee":0,
        "discount": 0,
        "notes":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        "product_id": 9,
        "total_price":"2222"
}

### delete a order
DELETE {{url}}/orders/1/ HTTP/1.1
