openapi: 3.0.0
info:
  title: My API
  description: Documentación de la API de mi aplicación
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: API local
paths:
  /api/products/:
    get:
      summary: Obtener el listado de productos.
      description: Devuelve un listado de los productos registrados en la base de datos.
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: El ID del producto.
                          name:
                            type: string
                            description: El nombre del producto.
                          price:
                            type: number
                            description: El precio del producto.
                      description: El valor de los productos registrados.
                    name:
                      message: string
                      description: Mensaje de notificación

        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor


  /api/users/{id}:
    get:
      summary: Obtener un usuario por su ID
      description: Devuelve la información de un usuario específico usando su ID.
      parameters:
        - name: id
          in: path
          description: El ID del usuario.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor



components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
